#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES=''
DESCRIPTION='lamp.'
HOSTBIN='lamp'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
### Start by updating, upgrading, cleaning.
apt update && apt upgrade -y
apt autoremove -y
reboot

###Install Apache & Configure
install apache2 -y

###Apache FQDN FIX
echo "ServerName localhost" | sudo tee /etc/apache2/conf-available/fqdn.conf && sudo a2enconf fqdn

### Set up default .htaccess and rewrites
cat << EOF > /etc/apache2/sites-available/000-default.conf
<Directory /var/www/html>
AllowOverride All
</Directory>
EOF
chmod u+x /etc/apache2/sites-available/000-default.conf

a2enmod rewrite

### Set index.php
cat << EOF > /etc/apache2/mods-enabled/dir.conf
<IfModule mod_dir.c>
DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
</IfModule>
EOF
chmod u+x /etc/apache2/mods-enabled/dir.conf

###Configure & Install MySQL
mysql_config_file="/etc/mysql/my.cnf"

echo "mysql-server mysql-server/root_password password password" | sudo debconf-set-selections
echo "mysql-server mysql-server/root_password_again password password" | sudo debconf-set-selections

install mysql-server -y

sed -i "s/bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" ${mysql_config_file}

usermod -d /var/lib/mysql/ mysql
service mysql start

# Allow root access from any host
echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'secret' WITH GRANT OPTION" | mysql -u root --password=password
echo "GRANT PROXY ON ''@'' TO 'root'@'%' WITH GRANT OPTION" | mysql -u root --password=password

service mysql restart

###Install PHP & MODULES
install php php-curl php-gd php-intl php-mbstring php-mysql php-soap php-xml php-xmlrpc php-zip -y

###Configure info.php
cat << EOF > /var/www/html/info.php
<?php
phpinfo();
?>
EOF
chmod u+x /var/www/html/info.php

###Configure php.ini
cat << EOF > /etc/php/7.2/apache2/php.ini
error_reporting = E_COMPILE_ERROR | E_RECOVERABLE_ERROR | E_ERROR | E_CORE_ERROR
max_input_time = 30
error_log = /var/log/php/error.log
EOF
chmod u+x /etc/php/7.2/apache2/php.ini

###Log file
###if [ -f '/var/log/php' ]; then
###	echo "log php file found."
###else
###	echo "log php file not found. Installing..."
mkdir /var/log/php
###fi

chown www-data /var/log/php

### Set up rc.local to start apache, mysql
cat << EOF > /etc/rc.local
#!/bin/sh -e
###Start this way to avoid error with systemctl and services
apachectl -f /etc/apache2/apache2.conf
/etc/init.d/mysql start
export HOME=/etc/mysql
umask 007
[ -d /var/run/mysqld ] || install -m 755 -o mysql -g root -d /var/run/mysqld
/usr/sbin/mysqld &
exit 0
EOF
chmod u+x /etc/rc.local