#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES=''
DESCRIPTION='Basic installation of WordPress on a LAMP stack'
HOSTBIN='wp'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"
 
### Install WP-CLI
if [ ! -f '/usr/local/bin/wp' ]; then
	wget -O /tmp/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x /tmp/wp-cli.phar
	mv /tmp/wp-cli.phar /usr/local/bin/wp
fi

###Start Mysql
service mysql start

if ! mysql -u root -ppassword -e 'use wordpress'; then
	echo 'CREATE DATABASE wordpress' | mysql -u root -ppassword
fi

### Install WP
if [ -f '/var/www/html/wordpress/wp-config.php' ]; then
	echo "WordPress config file found."
else
	echo "WordPress config file not found. Installing..."
	wp core download --path=/var/www/html/wordpress/ --allow-root
	wp core config --path=/var/www/html/wordpress/ --dbhost=localhost --dbname=wordpress --dbuser=root --dbpass=password --allow-root
	chown -R www-data /var/www/html/wordpress/
	wget -O /var/www/html/wordpress/wp-content/object-cache.php https://raw.githubusercontent.com/Automattic/wp-memcached/master/object-cache.php
fi

### Set up wordpress .htaccess and rewrites
cat << EOF > /etc/apache2/sites-available/wordpress.conf
<Directory /var/www/html/wordpress/>
AllowOverride All
</Directory>
EOF
chmod u+x /etc/apache2/sites-available/wordpress.conf

a2ensite wordpress.conf